### ISSUE TITLE
Make it easy for packagers to run unit tests rather than the full integration suite

### ISSUE THREAD

**Issue by dvzrv** [etesync/pyetesync#12]
I'm having troubles with failing tests in version 0.6.1.
[python-etesync-0.6.1.txt](https://github.com/etesync/pyetesync/files/2824540/python-etesync-0.6.1.txt)

They seem to be related to the local tests of the collections failing on urllib3.

**Comment by tasn** [comment]
I think the problem you're encountering is that some of the tests are integration tests (as in they work against an actual EteSync server). I just updated the readme, please check it out.

**Comment by dvzrv** [comment]
Hm, wouldn't it be better to move them to a different test file then?
It would be easier to trigger them separately/ exclude them then.

**Comment by dvzrv** [comment]
This way someone packaging has to specifically disable tests by name. And theoretically this could change anytime. This doesn't scale.

**Comment by tasn** [comment]
Arch complained about it before too, see their comments there: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/python-etesync

I can potentially add a file called:"run_unit_tests.sh". That will just trigger the correct tests being run. Would that solve it in your pov?

Also, I'm reopening this and renaming the title to better describe what we are talking about.

Thanks for reporting!

**Comment by tasn** [comment]
I guess I'll also add an "run_all_tests.sh" to run the whole thing which would be useful for developers.

**Comment by tasn** [comment]
Ah, it was you indeed, and actually, it is my fault this time, and I'm sorry. I mixed integration tests with the unit tests!

I'm at FOSDEM at the moment, so not sure if I can do it before Monday, but I'll try!

**Comment by tasn** [comment]
Done.
