### ISSUE TITLE
0.8.4: TestCollection::test_{crud,content,unicode} fail

### ISSUE THREAD

**Issue by dvzrv** [etesync/pyetesync#13]
Hi! I'm currently trying to package 0.8.4 for Arch Linux.
During the test session, the tests TestCollection::test_{crud,content,unicode} fail: 
[python-etesync-0.8.4-test.txt](https://github.com/etesync/pyetesync/files/3381220/python-etesync-0.8.4-test.txt)
It seems the latest changes for sqlite broke something there.

Builit with:
* python: 3.7.3
* python-appdirs: 1.4.3
* python-asn1crypto: 0.24.0
* python-cffi: 1.12.3
* python-coverage: 4.5.3
* python-cryptography: 2.7
* python-dateutil: 2.8.0
* python-furl: 2.0.0
* python-idna: 2.8
* python-orderedmultidict: 1.0
* python-packaging: 19.0
* python-peewee: 3.9.6
* python-py: 1.8.0
* python-pyasn1: 0.4.5
* python-pycparser: 2.19
* python-pyparsing: 2.4.0
* python-pytz: 2019.1
* python-requests: 2.22.0
* python-scrypt: 0.8.7
* python-six: 1.12.0
* python-vobject: 0.9.6.1

May I suggest setting up a continuous integration pipeline (using e.g. travis) to test against several target python versions with tox? This could detect problems like these much earlier (on pull request).

**Comment by tasn** [comment]
I 100% agree. I put it off for too long, but it enabled me to be sloppy (like this time) and not run the suite.
Please ignore this version, I'll release a new one after I fixed CI and this issue.

Thanks for reporting.
