### ISSUE TITLE
Remove testing dependencies from PyPi package

### ISSUE THREAD

**Issue by ironhouzi** [etesync/pyetesync#15]
I don't understand why `python-coverage` was listed as a dependency when installing from AUR.
I see in the `setup.py` that coverage is indeed listed.

I can offer to help out with some changes. What I like to do is to use `pip-compile` (from AUR `pip-tools`) to generate a solid `requirements.txt` file from `setup.py` and create two separate requirements-files if a `requirements.txt` file is needed for production. `pip-compile` will list the origin of all sub-dependencies, which is also really helpful.

To give a better impression, here's the output I generated from your `setup.py`:

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file=requirements.txt setup.py
#
appdirs==1.4.3
asn1crypto==0.24.0
attrs==19.1.0             # via packaging
certifi==2019.6.16        # via requests
cffi==1.12.3
chardet==3.0.4            # via requests
coverage==4.5.4
cryptography==2.7
furl==2.0.0
idna==2.8
orderedmultidict==1.0.1
packaging==19.1
peewee==3.10.0
py==1.8.0
pyasn1==0.4.6
pycparser==2.19
pyparsing==2.4.2
pyscrypt==1.6.2
python-dateutil==2.8.0
pytz==2019.2
requests==2.22.0
six==1.12.0
urllib3==1.25.3           # via requests
vobject==0.9.6.1
```
If you're interested in having this changed, I can provide a more detailed explanation of the change proposal.

**Comment by tasn** [comment]
Oops, nice catch! Yes, a PR would be of great help, and would love to see
your process so I can replicate with etesync-dav and server-skeleton.

Thanks!

**Comment by ironhouzi** [comment]
To clarify the workflow for development, you would need to install `pip-compile` and follow the instructions printed in the header of the requirements files.

To add new requirements, add it to `setup.py` if it's a runtime requirement, or to `requirements.in/development.txt` if it's only needed for development. Then rerun the commands as they are shown in the headers for each requirements file.

**Comment by ironhouzi** [comment]
I also wanted to change the AUR package to remove the `coverage` dependency, but I'm not sure how to go about doing that.

**Comment by tasn** [comment]
You just changed everything! :scream: 
Thanks a lot for introducing me to `pip-compile`, it's going to be a life changer. I've previously looked at requirements managers but never took the plunge. I will now.

As for AUR: it's not in AUR, that's why. :) It's in community... Let me first release a new version with the fix deps and then we can nudge the maintainer.

Thanks again!

**Comment by tasn** [comment]
Done, and also migrated https://github.com/etesync/etesync-dav !
