### ISSUE TITLE
contradicting file-based and project-wide licensing

### ISSUE THREAD

**Issue by jonassmedegaard** [etesync/pyetesync#18]
The project recently added explicit per-file copyright and licensing statements. Cool!

However, the added licensing is GPL-3, whereas the project-wide metadata in setup.py and LICENSE files indicate a licensing of LGPL-3.0-only.

It smells like an error.  If it really is intentional that general licensing of LGPL-3.0-only applies where there is no explicit different licensing, then I recommend to state that e.g. at the top of LICENSE or in README.md.

**Comment by tasn** [comment]
Yeah, it was just a copy-paste from the etesync-dav code. I forgot this one is LGPL when doing it. Will fix now. Thanks!
