### ISSUE TITLE
exchange pyscrypt with scrypt

### ISSUE THREAD

**Issue by dvzrv** [etesync/pyetesync#4]
Would [scrypt](https://pypi.python.org/pypi/scrypt/) not be a good alternative to [pyscrypt](https://pypi.python.org/pypi/pyscrypt)?

**Comment by tasn** [comment]
I didn't know about scrypt. Is it faster? Because pyscrypt is damn slow.
What would you say the main differences, or the reason to switch now?

**Comment by dvzrv** [comment]
Judging from the scrypt information given in the link above, it is reasonably fast.

Honestly, I don't know much about either implementation, but scrypt (from reading) seems to be the more widely adopted, too and using it seems pretty straight forward.
On the other hand pyscrypt hasn't been developed much further, is slow and has not found wide adoption (probably for a reason).

As python-etesync (or pyetesync) is an optdepends to vdirsyncer, I had to package all of python-etesync's dependencies as well when I moved vdirsyncer to the official Arch Linux [community] repository. I would rather do without python-pyscrypt, as we already have python-scrypt.

**Comment by tasn** [comment]
Fixed. Please get vdirsyncer to update their requirements to the latest pyetesync.

**Comment by tasn** [comment]
Btw, I just looked, and you have a mistake in the description of the "furl" package. I know this is not the place to report it, but since I already have your attention. :)

**Comment by dvzrv** [comment]
Damn, you're fast!
Thanks! I can drop a package!

I'll have a look, thanks for reminding! It was dependency hell yesterday...

**Comment by dvzrv** [comment]
> Please get vdirsyncer to update their requirements to the latest pyetesync.

I'll just update to the latest python-etesync. vdirsyncer's requirement is not bound to a version of pyetesync.

**Comment by tasn** [comment]
Ah, right, you're packaging it yourself, so no need to let them know.

I'm sorry about my contributions to this hell. I didn't think about packagers when making this, because pip just drags everything automatically, so it was not an issue for most users. This is indeed a concern though, and I'll try to be nicer in future versions. :)

Please let me know if you have any other deps you think I should want to/be able to drop.

**Comment by dvzrv** [comment]
No worries. vdirsyncer had way more dependencies I had to build and move ;-)
And it's only the checkdepends of an optdepends of a package, that I want to move... see? ;-)

**Comment by tasn** [comment]
Just for future reference: recent versions of pyetesync no longer require an external dependency for scrypt, and instead just use the one shipped with Python starting from Python 3.6.
