### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by dvzrv** [etesync/pyetesync#5]
Currently I'm not really running any of the tests, but I would like to.
How do I do that [during packaging](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/python-etesync)?

Usually I'd do something like `python setup.py test` to run the tests, but that's not implemented there.
If I run python on the tests subfolder, it doesn't work either

**Comment by tasn** [comment]
I just run "py.test" in the main source directory. I can look into integrating it into setuptools, it [doesn't seem to be too hard](https://docs.pytest.org/en/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner), though I don't have time at the moment.

Btw, python-coverage is only required for coverage reports, not normal running. This was my first published python package, and it looks like I made a bit of a mess there with the deps. O_o

**Comment by dvzrv** [comment]
The last test fails then. I attached the log:

[python-etesync.txt](https://github.com/etesync/pyetesync/files/1695416/python-etesync.txt)

**Comment by tasn** [comment]
Oh, sorry, I should have mentioned. The last test is an integration test with the server, and it requires a running etesync server to execute. You should probably just tell py.test to skip that one.

**Comment by dvzrv** [comment]
Okay. How do I do that? Sorry, I'm not that familiar with py.test.

**Comment by tasn** [comment]
I'm not sure if there's a way to explicitly skip without me having to implement it in the tests them selves, but one way for you to do it now would be running pytest as follows:

```
$ pytest tests/{test_collections.py,test_crypto.py}
```

**Comment by dvzrv** [comment]
Alright, this fixed it. Thanks!

**Comment by tasn** [comment]
For posterity: the scripts are no longer needed, and you can just run `pytest` directly, without any parameters, and it will only run the unit tests (unless you set a special env var).

**Comment by tasn** [comment]
Just to clarify: the above only applies to `master` and not yet to a release version. It will be available in 0.12.0.

**Comment by dvzrv** [comment]
On 2020-04-02 06:09:40 (-0700), Tom Hacohen wrote:
> Just to clarify: the above only applies to `master` and not yet to a
> release version. It will be available in 0.12.0.

No worries. I already found that out :D

**Comment by tasn** [comment]
Sorry :see_no_evil:
