### ISSUE TITLE
Don't install tests below 'site-packages'

### ISSUE THREAD

**Issue by dvzrv** [etesync/pyetesync#7]
When using

```
  python setup.py install --skip-build \
    --optimize=1 \
    --prefix=/usr \
    --root="${pkgdir}"

```
[during the package() function](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/python-etesync#n51), when building python-etesync for Arch Linux,  the `tests` folder ends up in `/usr/lib/python3.6/site-packages`
This however is not a valid location, as it [potentially conflicts with other packages](https://bugs.archlinux.org/task/57562) and should therefore not be chosen.

I will for now delete the tests folder during packaging, but it would be good, if the location could be fixed here.

**Comment by tasn** [comment]
Released and published a new version that includes the fix.

Sorry!
