### ISSUE TITLE
0.5.4 not available as source through pypi

### ISSUE THREAD

**Issue by dvzrv** [etesync/pyetesync#8]
On pypi only a wheel package of 0.5.4 is available.
When looking at the history, source packages are available up until 0.5.2, but not onwards (only wheel).
It would be great to also make the latest version available as source packages (also there are no accompanying tags on github? oO )!

**Comment by tasn** [comment]
Fixed, and also uploaded the tags, sorry about that!

Not sure what you meant by the second comment though.

**Comment by dvzrv** [comment]
well, pyscrypt is not in the official repositories, yet (scrypt is). Now I'll have to package it as well to ship pyetesync.

**Comment by tasn** [comment]
I can just make it an optional dep, so if it finds scrypt it uses it, but
otherwise it uses pyscrypt. That would fix it for you, but still keep the
pip path easy and portable... Thoughts?

**Comment by dvzrv** [comment]
That sounds like a great option! I would be very happy about it! :)

**Comment by tasn** [comment]
Btw, one issue I foresee: pyetesync depends on peewee2.
According to peewee they've only deprecated stuff, but I only see issues, so maybe they removed them already. Can take a look if it's a problem.

Ref: http://docs.peewee-orm.com/en/latest/peewee/changes.html

**Comment by tasn** [comment]
@dvzrv I just released a new version of pyetesinc that also relies on peewee3, so everything should now be solved.
