### ISSUE TITLE
bufLen is called buflen in latest version of scrypt

### ISSUE THREAD

**Issue by nemanjan00** [etesync/pyetesync#9]
https://github.com/etesync/pyetesync/blob/13c5ad11a891bdc747bca54b185272394a1087b4/etesync/crypto.py#L18

**Comment by tasn** [comment]
Do you know starting from which version? Pretty annoying if they changed API. :|

**Comment by tasn** [comment]
Ah, it doesn't look like they, have, seems to just be a mistake in pyetesync.

Thanks for reporting.

**Comment by nemanjan00** [comment]
There are also a few more bugs I found. It does not want to work on Arch at all (or there is something wrong with my setup)

**Comment by tasn** [comment]
Interesting. What have you tried?
I use Arch, but I'm developing it in a venv. Let me know what you've tried, and I'll try to replicate it here.

**Comment by nemanjan00** [comment]
Ok, I made it all work... 

On line 99 of etesync/api.py I had to remove .encode()... 

I had to replace in line 18 of file etesync/crypto.py bufLen with buflen. 

And I also had to make some changes to vobject, to make it work with calcurse, but, I guess that is offtopic here...

**Comment by tasn** [comment]
Good find! I just also noticed that the tests don't pass. This is a crazy embarrassing mess-up on my side! Would you like to open a PR for the api.py change so you get credit for the fix? (I already fixed the other one).
